name: dolistku
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^3.2.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.2
  realm: ^3.3.0
  localstorage: ^5.0.0
  flutter_cupertino_datetime_picker: ^3.0.0
  intl: ^0.19.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter: 
  assets: 
    - lib/assets/logo.png
    - lib/assets/google.png
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo.png"

